# Default values for myappposition-accounts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/myappposition/myappposition-accounts
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
     igress.kubernetes.io/ssl-redirect: "true"
     kubernetes.io/ingress.class: nginx
     certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - auth.myapp.vyukov.ru
  tls:
    - secretName: auth-myapp-tls
      hosts:
        - auth.myapp.vyukov.ru

resources:
   limits:
    cpu: 1
    memory: 348Mi
   requests:
    cpu: 1
    memory: 348Mi

nodeSelector: {}

tolerations: []

affinity: {}
