urls:
 panelUrl: http://localhost:8082


security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

google:
  provider-id: google
  client:
    clientId: 710258409208-4p26kd7sfuh3fcd7dr16umq6n642kohj.apps.googleusercontent.com
    clientSecret: 7gPb_LKzuHstp5Pu3zsAlhZN
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: query
    scope: profile email
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
github:
  provider-id: github
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user


spring:
  messages:
    basename: i18n/messages

#logging:
#  level:
#    org.springframework.security: DEBUG